on:
  push:
    branches: [main]

name: Release

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  packages: write # to publish packages (npm publish)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to fetch code (actions/checkout)
      packages: write # to publish packages (npm publish)
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          registry-url: "https://npm.pkg.github.com"
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          $(pnpm bin)/lerna version
      - run: $(pnpm bin)/lerna publish from-package --force-publish --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm view @ghoullier/shared dependencies --json
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm view @ghoullier/app dependencies --json
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

